name: tree_python
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - conda-forge::ete3
  - conda-forge::matplotlib
  - conda-forge::biopython
  - anaconda::scipy
  - conda-forge::svgwrite
  - pandas
  - bioconda::mummer
  - anaconda::scikit-learn
